[hekad]

{%- set workers = grains.num_cpus + 1 %}
maxprocs={{ workers }}
base_dir="/var/cache/{{ service_name }}"

hostname="{{ pillar.get('linux',{}).get('system',{}).name|default(grains.host) }}"

max_message_size = 262144
max_process_inject = 1
max_timer_inject = 10
poolsize = 100
