[hekad]

{%- set workers = grains.num_cpus + 1 %}
maxprocs={{ workers }}
base_dir="/var/cache/{{ service_name }}"

hostname="{{ grains.fqdn.split('.')[0] }}"

max_message_size = {{ max_message_size }}
max_process_inject = 1
max_timer_inject = 10
poolsize = {{ poolsize }}
